name: Sync Forked Repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间00:00触发

steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Pull from remote repository
        run: |
          git remote add upstream https://github.com/AirportR/FullTclash.git
          git fetch upstream dev
          git checkout dev
          git pull upstream dev
      
      - name: Push to target repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
              
