name: Release FullTClash libs
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  linuxbuild386:
    name: build 386core version
    runs-on: ubuntu-latest
    container: docker.io/ubuntu:18.04
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: build linux 386 version
        run: |
          apt-get update
          apt install -y sudo curl wget unzip ca-certificates build-essential gcc-multilib git
          git clone https://github.com/AirportR/FullTclash.git -b dev
          cd FullTclash     
      - name: gomod1
        run: go mod init myclash
      - name: gomod2
        run: go mod tidy
      - name: Build 386
        run: CGO_ENABLED=1 GOOS=linux GOARCH=386 go build -buildmode=c-shared -o ./output/fulltclash-linux-386 ./libs/fulltclash.go
      - name: Upload  Asset 
        uses: actions/upload-artifact@v2
        with:
          name: fulltclash-386
          path: ./output/*
          if-no-files-found: error
        
  linuxbuildamd64:
    name: build amd64core version
    runs-on: ubuntu-latest
    container: docker.io/ubuntu:18.04
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: build linux amd64 version
        run: |
          apt-get update
          apt install -y sudo curl wget unzip ca-certificates build-essential gcc-multilib git
          git clone https://github.com/AirportR/FullTclash.git -b dev
          cd FullTclash     
      - name: gomod1
        run: go mod init myclash
      - name: gomod2
        run: go mod tidy
      - name: Build amd64
        run:  CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o ./output/fulltclash-linux-amd64 ./libs/fulltclash.go
      - name: Upload  Asset 
        uses: actions/upload-artifact@v2
        with:
          name: fulltclash-amd64
          path: ./output/*
          if-no-files-found: error
  linuxbuildarm64:
    name: build arm64core version
    runs-on: ubuntu-latest
    container: docker.io/ubuntu:18.04
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: build linux arm64 version
        run: |
          apt-get update
          apt install -y sudo curl wget unzip ca-certificates build-essential gcc-aarch64-linux-gnu git
          git clone https://github.com/AirportR/FullTclash.git -b dev
          cd FullTclash     
      - name: gomod1
        run: go mod init myclash
      - name: gomod2
        run: go mod tidy
      - name: Build arm64
        run: CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -o ./output/fulltclash-linux-arm64 ./libs/fulltclash.go
      - name: Upload  Asset 
        uses: actions/upload-artifact@v2
        with:
          name: fulltclash-arm64
          path: ./output/*
          if-no-files-found: error
  linuxbuilds930x:
    name: build s930xcore version
    runs-on: ubuntu-latest
    container: docker.io/ubuntu:18.04
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: build linux s930x version
        run: |
          apt-get update
          apt install -y sudo curl wget unzip ca-certificates build-essential gcc-s390x-linux-gnu git
          git clone https://github.com/AirportR/FullTclash.git -b dev
          cd FullTclash     
      - name: gomod1
        run: go mod init myclash
      - name: gomod2
        run: go mod tidy
      - name: Build s390x
        run: CGO_ENABLED=1 GOOS=linux GOARCH=s390x CC=s390x-linux-gnu-gcc go build -o ./output/fulltclash-linux-s386x ./libs/fulltclash.go
      - name: Upload  Asset 
        uses: actions/upload-artifact@v2
        with:
          name: fulltclash-s930x
          path: ./output/*
          if-no-files-found: error
