# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go build

on: [push,pull_request]


jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, ubuntu-20.04]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: gomod1
        run: go mod init myclash
      - name: gomod2
        run: go mod tidy
      - name: Build
        run: go build -buildmode=c-shared -o ./output/fulltclash-${{ matrix.os }}-amd64 ./libs/fulltclash.go
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: fulltclash-${{ matrix.os }}-amd64
          path: ./output/*
          if-no-files-found: error
